# Generated by Django 5.1.15 on 2026-04-29 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auditlog_user_user_institution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["email"]},
        ),
    ]
