# Generated by Django 5.1.15 on 2026-05-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_backfill_legacy_institution_claims"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendinginstitutionclaim",
            name="requester_note",
        ),
        migrations.AddField(
            model_name="pendinginstitutionclaim",
            name="requester_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional context the user provided when submitting the claim.",
                max_length=4000,
            ),
        ),
        migrations.AlterField(
            model_name="pendinginstitutionclaim",
            name="review_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Coordinator's note. Used as the rejection reason in the email.",
                max_length=4000,
            ),
        ),
    ]
