# Generated by Django 5.1.15 on 2026-04-29 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field', models.CharField(help_text="Name of the translatable field on the target model (e.g., 'description', 'common_family_name'). Modeltranslation will store the locale-suffixed value at <field>_<locale> on that model.", max_length=100)),
                ('locale', models.CharField(help_text="Target locale code (e.g., 'fr', 'de', 'es'). English (the default source) does not carry rows here.", max_length=10)),
                ('status', models.CharField(choices=[('mt_draft', 'Machine-translated draft'), ('writer_reviewed', 'Writer-reviewed (voice/idiom checked)'), ('human_approved', 'Human-approved (publishable)'), ('published', 'Published (live on site)')], default='mt_draft', max_length=20)),
                ('mt_provider', models.CharField(blank=True, default='deepl', help_text="Provider that produced the original draft (e.g., 'deepl', 'manual').", max_length=50)),
                ('mt_translated_at', models.DateTimeField(blank=True, null=True)),
                ('writer_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('human_approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="Reviewer notes — locked-term substitutions made by the writer-agent, voice-register changes, regional usage flags for the human reviewer's attention.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_statuses', to='contenttypes.contenttype')),
                ('human_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='i18n_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'translation statuses',
                'db_table': 'i18n_translation_status',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='i18n_ts_object_idx'), models.Index(fields=['locale', 'status'], name='i18n_ts_locale_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field', 'locale'), name='i18n_translationstatus_unique_target')],
            },
        ),
    ]
