# Generated by Django 5.1.15 on 2026-04-18 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0009_flag_offshore_localities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesHusbandry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, help_text='Gates public API + frontend teaser. Draft records are invisible to the public.')),
                ('water_temp_c_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('water_temp_c_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('water_ph_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('water_ph_max', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('water_hardness_dgh_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('water_hardness_dgh_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('water_hardness_dkh_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('water_hardness_dkh_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('water_flow', models.CharField(blank=True, choices=[('still', 'Still'), ('gentle', 'Gentle'), ('moderate', 'Moderate'), ('strong', 'Strong')], max_length=20)),
                ('water_notes', models.TextField(blank=True)),
                ('tank_min_volume_liters', models.PositiveIntegerField(blank=True, null=True)),
                ('tank_min_footprint_cm', models.CharField(blank=True, max_length=50)),
                ('tank_aquascape', models.TextField(blank=True)),
                ('tank_substrate', models.TextField(blank=True)),
                ('tank_cover', models.TextField(blank=True)),
                ('tank_notes', models.TextField(blank=True)),
                ('diet_accepted_foods', models.JSONField(blank=True, default=list)),
                ('diet_live_food_required', models.BooleanField(default=False)),
                ('diet_feeding_frequency', models.CharField(blank=True, max_length=100)),
                ('diet_notes', models.TextField(blank=True)),
                ('behavior_temperament', models.CharField(blank=True, max_length=200)),
                ('behavior_recommended_sex_ratio', models.CharField(blank=True, max_length=100)),
                ('behavior_schooling', models.CharField(blank=True, max_length=200)),
                ('behavior_community_compatibility', models.CharField(blank=True, max_length=300)),
                ('behavior_notes', models.TextField(blank=True)),
                ('breeding_spawning_mode', models.CharField(blank=True, choices=[('substrate_spawner', 'Substrate spawner'), ('mouthbrooder', 'Mouthbrooder'), ('annual_killi', 'Annual killifish'), ('bubble_nest', 'Bubble nest'), ('livebearer', 'Livebearer'), ('other', 'Other')], max_length=30)),
                ('breeding_triggers', models.TextField(blank=True)),
                ('breeding_egg_count_typical', models.CharField(blank=True, max_length=100)),
                ('breeding_fry_care', models.TextField(blank=True)),
                ('breeding_survival_bottlenecks', models.TextField(blank=True)),
                ('breeding_notes', models.TextField(blank=True)),
                ('difficulty_adult_size', models.CharField(blank=True, max_length=200)),
                ('difficulty_space_demand', models.CharField(blank=True, max_length=200)),
                ('difficulty_temperament_challenge', models.CharField(blank=True, max_length=300)),
                ('difficulty_water_parameter_demand', models.CharField(blank=True, max_length=300)),
                ('difficulty_dietary_specialization', models.CharField(blank=True, max_length=300)),
                ('difficulty_breeding_complexity', models.CharField(blank=True, max_length=300)),
                ('difficulty_other', models.CharField(blank=True, max_length=300)),
                ('sourcing_cares_registered_breeders', models.BooleanField(default=False)),
                ('sourcing_notes', models.TextField(blank=True)),
                ('narrative', models.TextField(blank=True)),
                ('contributors', models.TextField(blank=True, help_text='Free text at MVP. Structured contributor records are post-MVP (BA §5).')),
                ('last_reviewed_at', models.DateField(blank=True, help_text='Required when published=True.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reviewed_by', models.ForeignKey(blank=True, help_text='Required when published=True.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_husbandry', to=settings.AUTH_USER_MODEL)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='husbandry', to='species.species')),
            ],
            options={
                'verbose_name': 'Species husbandry record',
                'verbose_name_plural': 'Species husbandry records',
                'db_table': 'husbandry_specieshusbandry',
                'ordering': ('species__scientific_name',),
            },
        ),
        migrations.CreateModel(
            name='HusbandrySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('husbandry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='husbandry.specieshusbandry')),
            ],
            options={
                'db_table': 'husbandry_husbandrysource',
                'ordering': ('order', 'id'),
            },
        ),
    ]
