# Generated by Django 5.1.15 on 2026-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('husbandry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specieshusbandry',
            name='behavior_notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='behavior_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='behavior_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='behavior_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='breeding_notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='breeding_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='breeding_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='breeding_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='diet_notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='diet_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='diet_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='diet_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='narrative_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='narrative_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='narrative_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='narrative_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='sourcing_notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='sourcing_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='sourcing_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='sourcing_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='tank_notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='tank_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='tank_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='tank_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='water_notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='water_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='water_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specieshusbandry',
            name='water_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
