# Generated by Django 5.1.15 on 2026-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='records_created',
            field=models.IntegerField(default=0),
        ),
    ]
