# Generated by Django 5.1.15 on 2026-04-22 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("populations", "0002_alter_institution_institution_type"),
        ("species", "0018_resynthesize_svg_viewboxes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinatedProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("ssp", "AZA Species Survival Plan"),
                            ("eep", "EAZA Ex-situ Programme"),
                            ("cares", "CARES Priority Species"),
                            ("independent", "Independent coordinated program"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable program name, e.g. 'AZA SSP: Madagascar Rainbowfish'. Shown on the coordinator dashboard.",
                        max_length=300,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "target_population_size",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional demographic target per the program's plan.",
                        null=True,
                    ),
                ),
                (
                    "plan_summary",
                    models.TextField(
                        blank=True,
                        help_text="Short human summary of the current plan. Full plan docs link out.",
                    ),
                ),
                (
                    "plan_document_url",
                    models.URLField(
                        blank=True,
                        help_text="External link to the authoritative plan (PDF, Confluence, etc.).",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordinating_institution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Institution holding the studbook / coordination responsibility.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_programs_led",
                        to="populations.institution",
                    ),
                ),
                (
                    "enrolled_institutions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Institutions that have joined the program (not including the coordinator).",
                        related_name="coordinated_programs_enrolled",
                        to="populations.institution",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinated_programs",
                        to="species.species",
                    ),
                ),
                (
                    "studbook_keeper",
                    models.ForeignKey(
                        blank=True,
                        help_text="The named studbook keeper, if one is assigned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_programs_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "populations_coordinatedprogram",
                "ordering": ["species__scientific_name", "program_type"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("in_transit", "In transit"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "proposed_date",
                    models.DateField(help_text="Date the transfer was first proposed / logged."),
                ),
                ("planned_date", models.DateField(blank=True, null=True)),
                (
                    "actual_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the transfer actually completed. Required when status='completed'.",
                        null=True,
                    ),
                ),
                ("count_male", models.IntegerField(blank=True, null=True)),
                ("count_female", models.IntegerField(blank=True, null=True)),
                ("count_unsexed", models.IntegerField(blank=True, null=True)),
                (
                    "cites_reference",
                    models.CharField(
                        blank=True,
                        help_text="CITES permit or equivalent reference number for threatened species. Blank for non-CITES-listed species.",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordinated_program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: the program this transfer serves.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="populations.coordinatedprogram",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="populations.institution",
                    ),
                ),
                (
                    "source_institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="populations.institution",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="species.species",
                    ),
                ),
            ],
            options={
                "db_table": "populations_transfer",
                "ordering": ["-proposed_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="coordinatedprogram",
            constraint=models.UniqueConstraint(
                fields=("species", "program_type"), name="unique_species_programtype"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_institution", models.F("destination_institution")), _negated=True
                ),
                name="transfer_source_destination_distinct",
            ),
        ),
    ]
