# Generated by Django 5.1.15 on 2026-04-23 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("populations", "0003_coordinatedprogram_transfer_and_more"),
        ("species", "0018_resynthesize_svg_viewboxes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BreedingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("spawning", "Spawning"),
                            ("hatching", "Hatching"),
                            ("mortality", "Mortality"),
                            ("acquisition", "Acquisition"),
                            ("disposition", "Disposition"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "count_delta_male",
                    models.IntegerField(
                        blank=True,
                        help_text="Signed change in male count. Negative = loss.",
                        null=True,
                    ),
                ),
                ("count_delta_female", models.IntegerField(blank=True, null=True)),
                ("count_delta_unsexed", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeding_events",
                        to="populations.exsitupopulation",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breeding_events_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "populations_breedingevent",
                "ordering": ["-event_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["population", "-event_date"], name="populations_populat_13d5eb_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-event_date"], name="populations_event_t_541b53_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BreedingRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("breed", "Breed"),
                            ("non_breed", "Non-breed (hold)"),
                            ("transfer", "Transfer"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("superseded", "Superseded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "rationale",
                    models.TextField(
                        blank=True,
                        help_text="Why this recommendation. Copy from the SSP / EEP plan, planning meeting minutes, or coordinator's own reasoning.",
                    ),
                ),
                (
                    "issued_date",
                    models.DateField(help_text="When the recommendation was issued. Required."),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Target date for action, if the plan specifies one.",
                        null=True,
                    ),
                ),
                (
                    "outcome_notes",
                    models.TextField(
                        blank=True, help_text="Free text — what happened. Filled in at resolution."
                    ),
                ),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordinated_program",
                    models.ForeignKey(
                        blank=True,
                        help_text="The program this recommendation was issued under, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breeding_recommendations",
                        to="populations.coordinatedprogram",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breeding_recommendations_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breeding_recommendations_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_population",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific population this recommendation concerns, when applicable. Null for species-wide recommendations.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breeding_recommendations_source",
                        to="populations.exsitupopulation",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breeding_recommendations",
                        to="species.species",
                    ),
                ),
                (
                    "target_institution",
                    models.ForeignKey(
                        blank=True,
                        help_text="The institution the recommendation is directed to — e.g. 'breed at Bristol', 'transfer to Cologne'. Null for coordinator-wide calls.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breeding_recommendations_target",
                        to="populations.institution",
                    ),
                ),
            ],
            options={
                "db_table": "populations_breedingrecommendation",
                "ordering": ["-issued_date", "-priority"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority"], name="populations_status_d6daa3_idx"
                    ),
                    models.Index(
                        fields=["species", "status"], name="populations_species_26d321_idx"
                    ),
                ],
            },
        ),
    ]
