# Generated by Django 5.1.15 on 2026-04-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populations', '0004_breedingevent_breedingrecommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exsitupopulation',
            options={'ordering': ['species__scientific_name', 'institution__name']},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
    ]
