# Generated by Django 5.1.15 on 2026-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("populations", "0005_alter_exsitupopulation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinatedprogram",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("ssp", "AZA Species Survival Plan (SSP)"),
                    ("eep", "EAZA Ex-situ Programme (EEP)"),
                    ("cares", "CARES Priority Species"),
                    ("independent", "Independent coordinated program"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
