# Generated by Django 5.1.15 on 2026-05-01 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("populations", "0006_alter_coordinatedprogram_program_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exsitupopulation",
            name="last_edited_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set by the institution-scoped edit path only (populations.views.ExSituPopulationViewSet.perform_update). NULL means the row has never been edited via the API write surface.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exsitupopulation",
            name="last_edited_by_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="populations.institution",
            ),
        ),
        migrations.AddField(
            model_name="exsitupopulation",
            name="last_edited_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exsitupopulation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
