# Generated by Django 5.1.15 on 2026-04-16 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('populations', '0001_initial'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('region', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('planned', 'Planned')], default='planned', max_length=20)),
                ('funding_sources', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('focal_species', models.ManyToManyField(blank=True, related_name='field_programs', to='species.species')),
                ('lead_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_programs', to='populations.institution')),
                ('partner_institutions', models.ManyToManyField(blank=True, related_name='partner_programs', to='populations.institution')),
            ],
            options={
                'db_table': 'fieldwork_fieldprogram',
            },
        ),
    ]
