# Generated by Django 5.1.15 on 2026-04-16 15:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdpa_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=200)),
                ('iucn_category', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(max_length=100)),
                ('status_year', models.IntegerField(blank=True, null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'species_protectedarea',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200)),
                ('taxonomic_status', models.CharField(choices=[('described', 'Described'), ('undescribed_morphospecies', 'Undescribed Morphospecies'), ('species_complex', 'Species Complex'), ('uncertain', 'Uncertain')], default='described', max_length=30)),
                ('provisional_name', models.CharField(blank=True, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, max_length=200, null=True)),
                ('year_described', models.IntegerField(blank=True, null=True)),
                ('family', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('endemic_status', models.CharField(choices=[('endemic', 'Endemic'), ('native', 'Native'), ('introduced', 'Introduced')], default='endemic', max_length=20)),
                ('iucn_status', models.CharField(blank=True, choices=[('EX', 'Extinct'), ('EW', 'Extinct in the Wild'), ('CR', 'Critically Endangered'), ('EN', 'Endangered'), ('VU', 'Vulnerable'), ('NT', 'Near Threatened'), ('LC', 'Least Concern'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], max_length=5, null=True)),
                ('population_trend', models.CharField(blank=True, choices=[('increasing', 'Increasing'), ('stable', 'Stable'), ('decreasing', 'Decreasing'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('cares_status', models.CharField(blank=True, choices=[('CCR', 'CARES Critical'), ('CEN', 'CARES Endangered'), ('CVU', 'CARES Vulnerable'), ('CLC', 'CARES Least Concern')], max_length=5, null=True)),
                ('shoal_priority', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('ecology_notes', models.TextField(blank=True)),
                ('distribution_narrative', models.TextField(blank=True)),
                ('morphology', models.TextField(blank=True)),
                ('max_length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('habitat_type', models.CharField(blank=True, max_length=100)),
                ('iucn_taxon_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('fishbase_id', models.IntegerField(blank=True, null=True)),
                ('gbif_taxon_key', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'species',
                'db_table': 'species_species',
            },
        ),
        migrations.CreateModel(
            name='ConservationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EX', 'Extinct'), ('EW', 'Extinct in the Wild'), ('CR', 'Critically Endangered'), ('EN', 'Endangered'), ('VU', 'Vulnerable'), ('NT', 'Near Threatened'), ('LC', 'Least Concern'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], max_length=5)),
                ('criteria', models.CharField(blank=True, max_length=100)),
                ('assessor', models.CharField(blank=True, max_length=200)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('iucn_official', 'Iucn Official'), ('recommended_revision', 'Recommended Revision')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('accepted', 'Accepted'), ('pending_review', 'Pending Review'), ('under_revision', 'Under Revision'), ('superseded', 'Superseded')], default='accepted', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('flagged_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_assessments', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_assessments', to='species.species')),
            ],
            options={
                'db_table': 'species_conservationassessment',
            },
        ),
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(help_text='ISO 639-1 code: en, fr, mg', max_length=10)),
                ('is_preferred', models.BooleanField(default=False)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='species.species')),
            ],
            options={
                'db_table': 'species_commonname',
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('family', 'Family'), ('genus', 'Genus'), ('species', 'Species'), ('subspecies', 'Subspecies')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('common_family_name', models.CharField(blank=True, max_length=200)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='species.taxon')),
            ],
            options={
                'verbose_name_plural': 'taxa',
                'db_table': 'species_taxon',
            },
        ),
        migrations.AddField(
            model_name='species',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to='species.taxon'),
        ),
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hybas_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('pfafstetter_level', models.IntegerField()),
                ('pfafstetter_code', models.BigIntegerField()),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_basins', to='species.watershed')),
            ],
            options={
                'db_table': 'species_watershed',
            },
        ),
        migrations.CreateModel(
            name='SpeciesLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_name', models.CharField(max_length=300)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_generalized', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('water_body', models.CharField(blank=True, max_length=200)),
                ('water_body_type', models.CharField(blank=True, choices=[('river', 'River'), ('lake', 'Lake'), ('stream', 'Stream'), ('cave_system', 'Cave System'), ('wetland', 'Wetland'), ('estuary', 'Estuary')], max_length=20)),
                ('drainage_basin_name', models.CharField(blank=True, max_length=200)),
                ('locality_type', models.CharField(choices=[('type_locality', 'Type Locality'), ('collection_record', 'Collection Record'), ('literature_record', 'Literature Record'), ('observation', 'Observation')], max_length=30)),
                ('presence_status', models.CharField(choices=[('present', 'Present'), ('historically_present_extirpated', 'Historically Present Extirpated'), ('presence_unknown', 'Presence Unknown'), ('reintroduced', 'Reintroduced')], default='present', max_length=40)),
                ('source_citation', models.TextField()),
                ('year_collected', models.IntegerField(blank=True, null=True)),
                ('collector', models.CharField(blank=True, max_length=200)),
                ('coordinate_precision', models.CharField(choices=[('exact', 'Exact'), ('approximate', 'Approximate'), ('locality_centroid', 'Locality Centroid'), ('water_body_centroid', 'Water Body Centroid')], default='exact', max_length=25)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('location_key', models.CharField(editable=False, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='species.species')),
                ('drainage_basin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localities', to='species.watershed')),
            ],
            options={
                'verbose_name_plural': 'species localities',
                'db_table': 'species_specieslocality',
                'constraints': [models.UniqueConstraint(fields=('species', 'location_key', 'locality_type'), name='unique_species_location_type')],
            },
        ),
    ]
