# Generated by Django 5.1.15 on 2026-04-16 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_syncjob_records_created'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationassessment',
            name='last_sync_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='integration.syncjob'),
        ),
    ]
