# Generated by Django 5.1.15 on 2026-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_conservationassessment_last_sync_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='in_captivity',
            field=models.BooleanField(default=False),
        ),
    ]
