# Generated by Django 5.1.15 on 2026-04-17 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_species_in_captivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationassessment',
            name='conflict_acknowledged_assessment_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conservationassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conservationassessment',
            name='source',
            field=models.CharField(choices=[('iucn_official', 'Iucn Official'), ('recommended_revision', 'Recommended Revision'), ('manual_expert', 'Manual Expert')], max_length=30),
        ),
    ]
