# Generated by Django 5.1.15 on 2026-04-17 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0003_iucn_sync_beat_schedule"),
        ("species", "0004_manual_expert_and_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationassessment",
            name="iucn_assessment_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="conservationassessment",
            name="iucn_year_published",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="conservationassessment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("iucn_assessment_id__isnull", False)),
                fields=("iucn_assessment_id",),
                name="unique_iucn_assessment_id_when_set",
            ),
        ),
    ]
