# Generated by Django 5.1.15 on 2026-04-17 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_iucn_sync_beat_schedule'),
        ('species', '0005_conservationassessment_iucn_assessment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationStatusConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('resolution', models.CharField(blank=True, choices=[('accepted_iucn', 'Accepted Iucn'), ('retained_manual', 'Retained Manual'), ('reconciled', 'Reconciled'), ('dismissed', 'Dismissed')], max_length=20, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detected_by_sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_detected', to='integration.syncjob')),
                ('iucn_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iucn_conflicts', to='species.conservationassessment')),
                ('manual_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_conflicts', to='species.conservationassessment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='species.species')),
            ],
            options={
                'db_table': 'species_conservationstatusconflict',
                'indexes': [models.Index(fields=['status', '-detected_at'], name='species_con_status_f675d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('species', 'manual_assessment', 'iucn_assessment'), name='unique_conflict_per_assessment_pair')],
            },
        ),
    ]
