# Generated by Django 5.1.15 on 2026-04-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_flag_offshore_localities'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conservationstatusconflict',
            new_name='species_con_status_ac8e6b_idx',
            old_name='species_con_status_detect_idx',
        ),
    ]
