# Generated by Django 5.1.15 on 2026-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_rename_species_con_status_detect_idx_species_con_status_ac8e6b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='silhouette_svg',
            field=models.TextField(blank=True, help_text='Optional inline SVG markup for a species-specific silhouette shown on the public profile when no photograph is available. Paste the full <svg>…</svg> element; use a transparent fill and currentColor strokes/fills so the figure inherits theme color. Tier-5 only.'),
        ),
    ]
