# Generated by Django 5.1.15 on 2026-04-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_normalize_silhouette_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('family', models.CharField(max_length=100)),
                ('silhouette_svg', models.TextField(blank=True, help_text='Optional inline SVG markup for a genus-level silhouette shown on species profiles that lack their own SVG. Paste the full <svg>…</svg> element. Same authoring conventions as <code>Species.silhouette_svg</code>: include a <code>viewBox</code>, use <code>fill="currentColor"</code>, and omit <code>width</code>/<code>height</code> on the root &lt;svg&gt; — they are stripped on save so CSS can size the figure.')),
                ('silhouette_credit', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'genera',
                'db_table': 'species_genus',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='species',
            name='silhouette_svg',
            field=models.TextField(blank=True, help_text='Optional inline SVG markup for a species-specific silhouette shown on the public profile when no photograph is available. Paste the full <svg>…</svg> element. Authoring conventions: include a <code>viewBox</code> attribute (e.g. <code>viewBox="0 0 200 80"</code>), use <code>fill="currentColor"</code> on paths so the figure inherits theme color, and omit <code>width</code>/<code>height</code> on the root &lt;svg&gt; — they are stripped on save so CSS can size the figure (renders ~300px wide on the public profile). Tier-5 only.'),
        ),
        migrations.AddField(
            model_name='species',
            name='genus_fk',
            field=models.ForeignKey(blank=True, help_text='Authoritative link to the genus record. Nullable during Gate 1 rollout; will tighten to NOT NULL in migration 0015.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='species', to='species.genus'),
        ),
    ]
