# Generated by Django 5.1.15 on 2026-04-20 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0014_populate_genus_and_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='genus_fk',
            field=models.ForeignKey(help_text='Authoritative link to the genus record. The string column ``genus`` is retained for this gate; drop is deferred to Gate 2.', on_delete=django.db.models.deletion.PROTECT, related_name='species', to='species.genus'),
        ),
    ]
