# Generated by Django 5.1.15 on 2026-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0015_tighten_genus_fk_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMapAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('hero_thumb', 'Home hero thumbnail (~160×320)'), ('profile_panel', 'Profile distribution panel (~180×360)')], help_text='Fixed slot consumed by a specific page region.', max_length=40, unique=True)),
                ('image', models.ImageField(blank=True, help_text='PNG or JPEG at or above the expected dimensions. Empty = no asset yet.', upload_to='site-maps/')),
                ('alt_text', models.CharField(blank=True, help_text='Screen-reader description of the thumbnail. Required when image is set.', max_length=300)),
                ('credit', models.CharField(blank=True, help_text='Attribution line shown alongside the image, if any.', max_length=200)),
                ('expected_width_px', models.PositiveIntegerField(help_text='Target render width in CSS pixels. Set when the slot is introduced.')),
                ('expected_height_px', models.PositiveIntegerField(help_text='Target render height in CSS pixels. Set when the slot is introduced.')),
                ('usage_notes', models.TextField(blank=True, help_text='Internal notes for editors — where the asset renders, sourcing guidance.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'species_sitemapasset',
                'ordering': ['slot'],
            },
        ),
    ]
