# Generated by Django 5.1.15 on 2026-04-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0019_species_location_sensitivity_backfill_generalized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protectedarea',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['scientific_name'], 'verbose_name_plural': 'species'},
        ),
        migrations.AlterModelOptions(
            name='watershed',
            options={'ordering': ['name']},
        ),
    ]
