# Generated by Django 5.1.15 on 2026-04-29 20:08
#
# Gate L1 — i18n. Adds language-suffixed columns for the translatable
# fields registered in `species/translation.py`. Modeltranslation's
# descriptor on the unsuffixed attribute reads/writes
# `<field>_<active_lang>`, so existing English content sitting on the
# unsuffixed columns is invisible after this migration UNTIL the
# `backfill_default_language_columns` operation copies it into the
# `_en` columns. The unsuffixed columns themselves are kept (not
# dropped) as a safety net per architect doc §4 / D15 — they're no
# longer read by the descriptor but retain pre-i18n data for any
# downstream system that hasn't migrated to language-aware reads yet.

from django.db import migrations, models


def backfill_default_language_columns(apps, schema_editor):
    Species = apps.get_model('species', 'Species')
    Species.objects.update(
        description_en=models.F('description'),
        ecology_notes_en=models.F('ecology_notes'),
        distribution_narrative_en=models.F('distribution_narrative'),
        morphology_en=models.F('morphology'),
    )
    Taxon = apps.get_model('species', 'Taxon')
    Taxon.objects.update(
        common_family_name_en=models.F('common_family_name'),
    )


def reverse_backfill(apps, schema_editor):
    # Reversing this migration drops the _en columns via the
    # AddField reversals; the data goes with them. The unsuffixed
    # columns are unchanged.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0020_alter_protectedarea_options_alter_species_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='distribution_narrative_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='distribution_narrative_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='distribution_narrative_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='distribution_narrative_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='ecology_notes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='ecology_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='ecology_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='ecology_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='morphology_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='morphology_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='morphology_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='morphology_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='common_family_name_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='common_family_name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='common_family_name_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='common_family_name_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(
            backfill_default_language_columns,
            reverse_backfill,
        ),
    ]
