# Generated by Django 5.1.15 on 2026-04-17 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integration", "0003_iucn_sync_beat_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.PositiveIntegerField()),
                ("field", models.CharField(blank=True, default="", max_length=100)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System")], max_length=10
                    ),
                ),
                ("actor_system", models.CharField(blank=True, default="", max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("mirror_write", "Mirror Write"),
                            ("conflict_detected", "Conflict Detected"),
                            ("conflict_resolved", "Conflict Resolved"),
                        ],
                        max_length=30,
                    ),
                ),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="integration.syncjob",
                    ),
                ),
            ],
            options={
                "db_table": "audit_entry",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "-timestamp"],
                        name="audit_target_time_idx",
                    ),
                    models.Index(fields=["actor_type", "-timestamp"], name="audit_actor_time_idx"),
                ],
            },
        ),
    ]
