# Generated by Django 5.1.15 on 2026-05-01 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        ("populations", "0007_exsitupopulation_last_edited_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditentry",
            name="actor_institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Snapshot of the actor's institution at edit time. Defends against later User.institution reassignment obscuring history.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="populations.institution",
            ),
        ),
    ]
